

project:
  name: "radar_controlnet"
  output_dir: "output/controlnet_fixed_loss_1017"
  # TensorBoard: tensorboard --logdir=output/controlnet_fixed_loss/logs

data:
  data_dir: "new_data"
  resolution: 512
  range_max: 200
  vel_max: 40

training:
  train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 100               
  
  learning_rate: 1e-7                 
  lr_scheduler: "cosine"
  lr_warmup_steps: 4500            
  max_grad_norm: 0.5                  
  
  save_steps: 9000
  mixed_precision: "fp16"
  dataloader_num_workers: 4
  
  
  loss_weight_factor: 100.0           
  use_focal_loss: false               
  
  heatmap_sigma: 8.0                  


