# 雷达 RD 图 ControlNet 训练配置
project:
  name: "radar_controlnet"
  output_dir: "output/radar_controlnet"


  data_dir: "your_dataset"   # ← 改成你的数据集路径！
  resolution: 512
  range_max: 200             # 距离最大值（米）
  vel_max: 40                # 速度最大绝对值（m/s）

training:
  train_batch_size: 1        # 每卡 batch size
  gradient_accumulation_steps: 8   # 有效 batch = 1 * 8 = 8
  num_train_epochs: 15
  learning_rate: 1.0e-5
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  max_grad_norm: 1.0
  save_steps: 500            # 每 500 步保存 checkpoint
  mixed_precision: "fp16"
  dataloader_num_workers: 4