

project:
  name: "radar_controlnet"
  output_dir: "output/controlnet_fixed_loss"
  # TensorBoard: tensorboard --logdir=output/controlnet_fixed_loss/logs

data:
  data_dir: "dataset"
  resolution: 512
  range_max: 200
  vel_max: 40

training:
  train_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 80               
  
  learning_rate: 8e-6                 
  lr_scheduler: "cosine"
  lr_warmup_steps: 2000               
  max_grad_norm: 0.5                  
  
  save_steps: 4210
  mixed_precision: "fp16"
  dataloader_num_workers: 4
  
  
  loss_weight_factor: 100.0           
  use_focal_loss: false               
  
  heatmap_sigma: 8.0                  


